version: '3.8'

services:
  db:
    image: postgres:16.0
    container_name: db_dev_negocio_seguro
    restart: always
    environment:
      POSTGRES_DB: dev_negocio_seguro
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5433:5432
